### PR TITLE
Theme music

### PR DESCRIPTION
**Pull request by vanjackson**
added ThemeMusic.java file and edited TitleScreen to add a button that enables the playMusic method.

### CODE REVIEW

**Comment by tss47** [comment]
Resolved merge conflict, code is tested on my local repository and works. Enjoy the tune, courtesy of Maestro Van.

**Comment by SamuelWolfe** [comment]
Fantastic Work on the tunes.

**Comment by kqs2** [comment]
Yay music!

**Comment by Mackie-Le53** [comment]
Whoop whoop

**Pull request merged**
